name = 'spaces-website'
pages_build_output_dir = "public"

[build]
command = "curl -sL https://github.com/getzola/zola/releases/download/v0.22.1/zola-v0.22.1-x86_64-unknown-linux-gnu.tar.gz | tar xz && ./zola build"

[vars]
ZOLA_VERSION = "0.22.1"
